[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.5.0-alpha.0", features = ["fullstack"]}
dioxus-fullstack = "0.5.0-alpha.0"

[features]
default = []
server = ["dioxus/axum"]
web = ["dioxus/web"]
